### ISSUE TITLE
Problem with babel lang in 2.1.0

### ISSUE THREAD

**Issue by eumesmamente** [Wandmalfarbe/pandoc-latex-template#312] opened 2022-12-10 23:16 UTC
With pandoc 2.8 I have the following problem:

```
pandoc cinema.md -o cinema_aula.pdf --from markdown+raw_tex --template ./eisvogel.latex  --filter pandoc-latex-environment --listings --number-sections -Vsecnumdepth=3 -V lang=gl-ES

Error producing PDF.
! Package babel Error: You haven't specified a language option.

See the babel package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.478 ...ry to proceed from here, type x to quit.}
```

I am using galician language. With a previous version it worked without problems with -V lang=gl-ES but now I have tried with galician, gl, in the command line and with lang: galician, lang:gl, lang: gl-ES in YAML but the problem persists. A bug or am I doing something wrong ?

**Comment by Wandmalfarbe** [comment] 2022-12-11 15:38
In the upstream repository, there were some changes related to the document language:

* https://github.com/jgm/pandoc/commit/dd7b83ac9111b63786c1042c4849d7cea79c668b
* https://github.com/jgm/pandoc/commit/da8bcb783b1f5fc99be86617762eca42ab2db6ad
* https://github.com/jgm/pandoc/commit/3f489bcb5897898d453bef549d6eba5f5d2120bf
* https://github.com/jgm/pandoc/commit/bc7f74968e5feb1174ac048b5e97fee97e537ef8

I merged these changes into [Eisvogel version 2.1.0](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/tag/v2.1.0). Are you using the latest Eisvogel version? Are you using the [latest Pandoc version](https://github.com/jgm/pandoc/releases)?

I can't reproduce your issue. Maybe you can attach the complete reproduction? My reproduction is attached and compiles just fine. The file `output/document-eisvogel.tex` confirms that Galician is used (in lines 108 and 121).

[issue-312-language-galician.zip](https://github.com/Wandmalfarbe/pandoc-latex-template/files/10202548/issue-312-language-galician.zip)

**Comment by Wandmalfarbe** [comment] 2022-12-12 19:04
I see that you get the error with the pandoc default template and with Eisvogel. So this looks like an outdated LaTeX distribution. Can you update to the lastest version and try again?

**Comment by eumesmamente** [comment] 2022-12-18 15:29
No problem on ubuntu 20.04. Thanks.

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode

(/home/user/Documentos/issue-312-language-galician/issue-312-language-galician/output/.document-default.tex.swp
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
...
Output written on /home/user/.cache/gummi/.document-default.tex.pdf (2 pages,
 177288 bytes).
Transcript written on /home/user/.cache/gummi/.document-default.tex.log.
```

**Closed** 2022-12-19 16:24 UTC
