### ISSUE TITLE
verbatim text?

### ISSUE THREAD

**Issue by pazz** [Wandmalfarbe/pandoc-latex-template#236] opened 2021-04-11 17:54 UTC
Hi,

I saw that there are some issues with defining verbatim text but I was not able to replicate this, hence the new issue:

How can I have a verbatim text block to display the content of a text file without any syntax highlighting?
I would also like to keep using the default settings for the listings package to display (Java) code snippets in other places.
Any help would be much appreciated!

**Comment by Wandmalfarbe** [comment] 2021-04-20 21:30
You can either use listings to render code blocks or you can leave everything to pandoc (where verbatim gets used eventually). When you use listings, the default language for all code blocks is Java at the moment (see issue #192). You can however change the language of individual code blocks manually to `txt`, which will only work when using verbatim. 

````md
```txt
public class Example implements LoremIpsum {
	public static void main(String[] args) {
		if(args.length < 2) {
			System.out.println("Lorem ipsum dolor sit amet");
		}
	} // Obscura atque coniuge, per de coniunx
}
```
````

If you use listings the default language will be Java even if you specify `txt` on your code blocks.

**Comment by Wandmalfarbe** [comment] 2021-04-20 21:32
Duplicate of #192.

**Closed by Wandmalfarbe** 2021-04-20 21:32 UTC

**Comment by pazz** [comment] 2021-04-21 08:33
Great, thank you! I was not aware of the "txt" block and instead tried text, verbatim etc.
Cheers!
